name: CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8.0.192, 8, 11.0.3, 11, 15 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'zulu'
    - name: Build with Maven
      if: ${{ !startsWith(matrix.java-version, '15') }}
      run: mvn -B package --file pom.xml -DdisableToolchain
    - name: Build with Maven with help active profile
      if: ${{ startsWith(matrix.java-version, '15') }}
      run: mvn -B help:active-profiles && mvn -B package --file pom.xml -DdisableToolchain
